use std::sync::Arc;

use crate::squic::SunnyCredential;
use crate::msgs::squic::SUNNY_QUIC_AUTH_LEN;

pub mod inbound;
pub mod outbound;

#[cfg(any(feature = "sunnyquic-gm-quic", feature = "sunnyquic-iroh-quinn"))]
pub(crate) mod dynamic_cert;

#[cfg(feature = "sunnyquic-gm-quic")]
mod gm_quic_wrapper;
#[cfg(feature = "sunnyquic-gm-quic")]
pub use gm_quic_wrapper::{Connection, EndClient, EndServer};

#[cfg(feature = "sunnyquic-iroh-quinn")]
mod iroh_wrapper;
#[cfg(feature = "sunnyquic-iroh-quinn")]
pub use iroh_wrapper::{Connection, EndClient, EndServer};

///
#[cfg(all(
    not(feature = "sunnyquic-iroh-quinn"),
    not(feature = "sunnyquic-gm-quic")
))]
mod unimplemented;
#[cfg(all(
    not(feature = "sunnyquic-iroh-quinn"),
    not(feature = "sunnyquic-gm-quic")
))]
pub use unimplemented::{Connection, EndClient, EndServer};

/// Generate sunnyquic user hash from username and password
/// The hash is generated by SHA256(username:password)
pub fn gen_sunny_user_hash(username: &str, password: &str) -> SunnyCredential {
    use ring::digest::{Context, SHA256};
    let mut ctx = Context::new(&SHA256);
    ctx.update(username.as_bytes());
    ctx.update(b":");
    ctx.update(password.as_bytes());
    let hash_out = ctx.finish();
    let mut arr = [0u8; SUNNY_QUIC_AUTH_LEN];
    let hash_bytes = hash_out.as_ref();
    let len = arr.len().min(hash_bytes.len());
    arr[..len].copy_from_slice(&hash_bytes[..len]);
    arr
}
