name: Release

on:
  push:
    tags: [ "v*" ]
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PACKAGE: "shadowquic"
  RUST_TOOLCHAIN: "stable"

jobs:
  compile:
    name: ${{ matrix.release-name || matrix.target || 'Unknown' }}
    permissions:
      contents: write
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            release-name: x86_64-linux
            tool: cross
            rustflags: "-C target-cpu=nehalem -C target-feature=+sse,+sse2"
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            release-name: i686-linux
            tool: cross
            rustflags: "-C target-feature=+sse,+sse2"
          # Linux x86 musl (optimized for different CPU generations)
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            release-name: x86_64-linux-musl-j1900
            tool: cross
            rustflags: "-C target-cpu=nehalem"
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            release-name: x86_64-linux-musl-j4125
            tool: cross
            rustflags: "-C target-cpu=goldmont"
          - os: ubuntu-latest
            target: i686-unknown-linux-musl
            release-name: i686-linux-musl
            tool: cross
            rustflags: "-C target-feature=+sse,+sse2"
          # Linux arm
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            release-name: aarch64-linux
            tool: cross
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabi
            release-name: armv7-linux
            tool: cross
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            release-name: armv7-linux-hf
            tool: cross
          # Linux arm musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            release-name: aarch64-linux-musl
            tool: cross
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabi
            release-name: armv7-linux-musl
            tool: cross
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            release-name: armv7-linux-muslhf
            tool: cross
          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            release-name: x86_64-windows
            postfix: ".exe"
            rustflags: "-C target-cpu=x86-64-v3"
          - os: windows-latest
            target: i686-pc-windows-msvc
            release-name: i686-windows
            postfix: ".exe"
            rustflags: "-C target-feature=+sse,+sse2"
          # Windows Arm
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            release-name: aarch64-windows
            postfix: ".exe"
            skip-test: true
          # MacOSX
          - os: macos-15-intel
            target: x86_64-apple-darwin
            release-name: x86_64-darwin
            rustflags: "-C target-cpu=x86-64-v3"
          - os: macos-14
            target: aarch64-apple-darwin
            release-name: aarch64-darwin
            rustflags: "-C target-cpu=apple-m1"
          # FreeBSD
          - os: ubuntu-latest
            target: x86_64-unknown-freebsd
            release-name: x86_64-freebsd
            tool: cross
            skip-test: true
          - os: ubuntu-latest
            target: i686-unknown-freebsd
            release-name: i686-freebsd
            tool: cross
            rustflags: "-C target-feature=+sse,+sse2"
            skip-test: true
          # RISC-V
          - os: ubuntu-latest
            target: riscv64gc-unknown-linux-gnu
            release-name: riscv64gc-linux
            tool: cross
          # Loongarch64
          - os: ubuntu-latest
            target: loongarch64-unknown-linux-gnu
            release-name: loongarch64-linux
            tool: cross
          # Android
          - os: ubuntu-latest
            target: aarch64-linux-android
            release-name: aarch64-android
            tool: cross
            skip-test: true
          - os: ubuntu-latest
            target: armv7-linux-androideabi
            release-name: armv7-android
            tool: cross
            skip-test: true
          - os: ubuntu-latest
            target: i686-linux-android
            release-name: i686-android
            tool: cross
            skip-test: true
          - os: ubuntu-latest
            target: x86_64-linux-android
            release-name: x86_64-android
            tool: cross
            skip-test: true
          # Linux mips
          - os: ubuntu-latest
            target: mips-unknown-linux-musl
            release-name: mips-linux-musl
            tool: cross
            toolchain: nightly
            install-target: false
            components: rust-src, rustfmt
            extra-args: "-Z build-std=std,panic_abort"
            skip-test: true
          - os: ubuntu-latest
            target: mipsel-unknown-linux-musl
            release-name: mipsel-linux-musl
            tool: cross
            toolchain: nightly
            install-target: false
            components: rust-src, rustfmt
            extra-args: "-Z build-std=std,panic_abort"
            skip-test: true
          - os: ubuntu-latest
            target: mips64-unknown-linux-muslabi64
            release-name: mips64-linux-musl
            tool: cross
            toolchain: nightly
            install-target: false
            components: rust-src, rustfmt
            extra-args: "-Z build-std=std,panic_abort"
            skip-test: true
          - os: ubuntu-latest
            target: mips64el-unknown-linux-muslabi64
            release-name: mips64el-linux-musl
            tool: cross
            toolchain: nightly
            install-target: false
            components: rust-src, rustfmt
            extra-args: "-Z build-std=std,panic_abort"
            skip-test: true

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ matrix.release-name || matrix.target }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ matrix.release-name || matrix.target }}

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain || env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.install-target != false && matrix.target || '' }}
          components: ${{ matrix.components || 'rustfmt' }}

      - name: Install rust targets & cross
        if: matrix.tool == 'cross'
        run: |
          if [ "${{ matrix.install-target }}" != "false" ]; then
            rustup target add ${TARGET}
          fi
          rm -f ~/.cargo/bin/cross*
          cargo install cross --git https://github.com/cross-rs/cross
        env:
          TARGET: ${{ matrix.target }}

      - name: Install Windows ARM target
        if: matrix.target == 'aarch64-pc-windows-msvc'
        run: rustup target add aarch64-pc-windows-msvc

      - name: Cargo build
        uses: clechasseur/rs-cargo@v4
        with:
          tool: ${{ matrix.tool }}
          command: build
          args: --workspace --release --target ${{ matrix.target }} ${{ matrix.extra-args }}
        env:
          CARGO_TERM_COLOR: always
          RUSTFLAGS: ${{ matrix.rustflags || '-C target-cpu=generic -C opt-level=3' }}
          CARGO_PROFILE_RELEASE_LTO: fat
          CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
          CARGO_PROFILE_RELEASE_STRIP: true
          CARGO_PROFILE_RELEASE_PANIC: abort

      - name: Rename binary
        run: mv target/${{ matrix.target }}/release/${{ env.PACKAGE }}${{ matrix.postfix }} ${{ env.PACKAGE }}-${{ matrix.release-name || matrix.target }}${{ matrix.postfix }}

      - name: Upload binaries
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.PACKAGE }}-${{ matrix.release-name || matrix.target }}
          path: ${{ env.PACKAGE }}-${{ matrix.release-name || matrix.target }}${{ matrix.postfix }}


  release:
    name: Release
    needs: [compile]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Merge binaries
        uses: actions/upload-artifact/merge@v6
        with:
          name: binaries
          pattern: '*'
          retention-days: 1

      - name: Download binaries
        uses: actions/download-artifact@v7
        with:
          name: binaries
          path: ./packages

      - name: Clean git tag & release
        if: startsWith(github.ref, 'refs/heads/dev')
        run: |
          gh release delete latest --cleanup-tag --yes --repo $GITHUB_REPOSITORY || true
          git tag -d latest || true
          git tag latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean git tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          git tag -d latest || true

      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: .github/cliff.toml
          args: --latest --strip header
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Github stable release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          generate_release_notes: false
          body: ${{ steps.git-cliff.outputs.content }}
          files: |
            packages/*
            LICENSE

      - name: Github nightly release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/heads/dev')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          generate_release_notes: false
          body: ${{ steps.git-cliff.outputs.content }}
          tag_name: "latest"
          files: |
            packages/*
            LICENSE

